version: '3'
services: 
  bdslocal:
    hostname: bdscentos
    image: "leophan/bdscentos:0.1.1"
    ports:
     - "2181:2181"
     - "9092:9092"
     - "9090:9090"
     - "9200:9200"
     - "9300:9300"
     - "5601:5601"
    #  - "6627:6627"
    #  - "8080:8080"
    #  - "6700:6700"
    #  - "6701:6701"
    #  - "6702:6702"
    #  - "6703:6703"
     - "6379:6379"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_PORT: 9092
      KAFKA_CREATE_TOPICS: "bdslab:1:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 3072M
        reservations:
          cpus: '0.30'
          memory: 2048M
        # restart_policy:
        #   condition: on-failure
        #   delay: 5s
        #   max_attempts: 3
        #   window: 120s